//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMCCONSULTAS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.materialescreativos.com/", ConfigurationName="WSMCCONSULTAS.WSpedidos")]
    public interface WSpedidos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.materialescreativos.com/WSpedidos/validaFolioRequest", ReplyAction="http://webservice.materialescreativos.com/WSpedidos/validaFolioResponse")]
        WSMCCONSULTAS.validaFolioResponse validaFolio(WSMCCONSULTAS.validaFolioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.materialescreativos.com/WSpedidos/validaFolioRequest", ReplyAction="http://webservice.materialescreativos.com/WSpedidos/validaFolioResponse")]
        System.Threading.Tasks.Task<WSMCCONSULTAS.validaFolioResponse> validaFolioAsync(WSMCCONSULTAS.validaFolioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaFolioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaFolio", Namespace="http://webservice.materialescreativos.com/", Order=0)]
        public WSMCCONSULTAS.validaFolioRequestBody Body;
        
        public validaFolioRequest()
        {
        }
        
        public validaFolioRequest(WSMCCONSULTAS.validaFolioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validaFolioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string datos;
        
        public validaFolioRequestBody()
        {
        }
        
        public validaFolioRequestBody(string datos)
        {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaFolioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaFolioResponse", Namespace="http://webservice.materialescreativos.com/", Order=0)]
        public WSMCCONSULTAS.validaFolioResponseBody Body;
        
        public validaFolioResponse()
        {
        }
        
        public validaFolioResponse(WSMCCONSULTAS.validaFolioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validaFolioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public validaFolioResponseBody()
        {
        }
        
        public validaFolioResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WSpedidosChannel : WSMCCONSULTAS.WSpedidos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WSpedidosClient : System.ServiceModel.ClientBase<WSMCCONSULTAS.WSpedidos>, WSMCCONSULTAS.WSpedidos
    {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        /// 

        public string validaFolio(string xml)
        {
            WSMCCONSULTAS.validaFolioRequest inValue = new WSMCCONSULTAS.validaFolioRequest();
            inValue.Body = new WSMCCONSULTAS.validaFolioRequestBody();
            inValue.Body.datos = xml;
            WSMCCONSULTAS.validaFolioResponse retVal = ((WSMCCONSULTAS.WSpedidos)(this)).validaFolio(inValue);
            return retVal.Body.@return;
        }


        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSpedidosClient() : 
                base(WSpedidosClient.GetDefaultBinding(), WSpedidosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSpedidosPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSpedidosClient(EndpointConfiguration endpointConfiguration) : 
                base(WSpedidosClient.GetBindingForEndpoint(endpointConfiguration), WSpedidosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSpedidosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSpedidosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSpedidosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSpedidosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSpedidosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WSMCCONSULTAS.validaFolioResponse validaFolio(WSMCCONSULTAS.validaFolioRequest request)
        {
            return base.Channel.validaFolio(request);
        }
        
        public System.Threading.Tasks.Task<WSMCCONSULTAS.validaFolioResponse> validaFolioAsync(WSMCCONSULTAS.validaFolioRequest request)
        {
            return base.Channel.validaFolioAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSpedidosPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSpedidosPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/WSpedidosMC/WSpedidos");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSpedidosClient.GetBindingForEndpoint(EndpointConfiguration.WSpedidosPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSpedidosClient.GetEndpointAddress(EndpointConfiguration.WSpedidosPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WSpedidosPort,
        }
    }
}
